export const SkillSeed = [
  {
    Image: "images/ethical-hacking.jpg",
    CourseCatagory: "Cybersecruity",
    CourseName: "Ethical Hacking Course",
    Duration: "50 days training",
    NumOfStudent: "24k students trained",
  },
  {
    Image: "images/web-development.jpg",
    CourseCatagory: "Web Development",
    CourseName: "Website Development Course",
    Duration: "50 days training",
    NumOfStudent: "24k students trained",
  },
  {
    Image: "images/penetration-testing-live-courses.jpg",
    CourseCatagory: "Cybersecruity",
    CourseName: "Penetration Testing Course",
    Duration: "4 months training",
    NumOfStudent: "21K+ students trained",
  },
  {
    Image: "images/data-science.webp",
    CourseCatagory: "Professional",
    CourseName: "Data Science Course",
    Duration: "6 months training",
    NumOfStudent: "400+ students trained",
  },
  {
    Image: "images/dm-course.webp",
    CourseCatagory: "Digital Marketing",
    CourseName: "SEO Course",
    Duration: "45 days training",
    NumOfStudent: "75K+ students trained",
  },
  {
    Image: "images/seo-course.jpg",
    CourseCatagory: "Digital Marketing",
    CourseName: "Content Writing Course",
    Duration: "60  days training",
    NumOfStudent: "500+ students trained",
  },
  {
    Image: "images/web-development.jpg",
    CourseCatagory: "Web Development",
    CourseName: "WordPress Course",
    Duration: "60  days training",
    NumOfStudent: "789+ students trained",
  },
  {
    Image: "images/python.jpg",
    CourseCatagory: "Programming",
    CourseName: "Python Programming Course",
    Duration: "5 days training",
    NumOfStudent: "4k+ students trained",
  },
  {
    Image: "images/android-development.jpg",
    CourseCatagory: "App Development",
    CourseName: "Android App Development Course",
    Duration: "90 days training",
    NumOfStudent: "20k+ students trained",
  },
  {
    Image: "images/web-development.jpg",
    CourseCatagory: "Web Development",
    CourseName: "Full-Stack Web Development Course",
    Duration: "6 months training",
    NumOfStudent: "50k+ students trained",
  },
];
